.TH "carray" 3 "Mon Sep 25 2017" "Version 0.1.3" "C-Array" \" -*- nroff -*-
.ad l
.nh
.SH NAME
carray \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <carray\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "type * \fB_array\fP"
.br
.ti -1c
.RI "size_t \fB_size\fP"
.br
.ti -1c
.RI "size_t \fB_space\fP"
.br
.ti -1c
.RI "size_t \fB_read_position\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Carray class implementation\&. Provides Python-like list for C\&. 
.PP
Definition at line 216 of file carray\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Array from the source code\&.
