.TH "cst_group" 3 "Mon Sep 25 2017" "Version 0.1.3" "C-Array" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cst_group \- Constants for C-Array class
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEFAULT_SPACE_INIT_FLAT\fP   8"
.br
.ti -1c
.RI "#define \fBDEFAULT_SPACE_INIT_PERCENT\fP   1\&.25"
.br
.ti -1c
.RI "#define \fBDEFAULT_SPACE_INCR\fP   2\&.0"
.br
.ti -1c
.RI "#define \fBDEFAULT_SHRINK_THRESHOLD\fP   2\&.5"
.br
.ti -1c
.RI "#define \fBDEFAULT_SHRINK_PERCENT\fP   1\&.25"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBcarray\fP \fBcarray\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DEFAULT_SHRINK_PERCENT   1\&.25"
Space factor used when the carray is shrinked\&. 
.PP
Definition at line 50 of file carray\&.h\&.
.SS "#define DEFAULT_SHRINK_THRESHOLD   2\&.5"
Space threshold from which the carray is shrinked\&. 
.PP
Definition at line 45 of file carray\&.h\&.
.SS "#define DEFAULT_SPACE_INCR   2\&.0"
Space factor used when a carray becomes too short\&. 
.PP
Definition at line 40 of file carray\&.h\&.
.SS "#define DEFAULT_SPACE_INIT_FLAT   8"
Initial space for the internal representation of a carray\&. 
.PP
Definition at line 30 of file carray\&.h\&.
.SS "#define DEFAULT_SPACE_INIT_PERCENT   1\&.25"
Initial space factor used when a carray is created from an existing one\&. 
.PP
Definition at line 35 of file carray\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBcarray\fP \fBcarray\fP"
Alias for carray struct\&. 
.PP
Definition at line 55 of file carray\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Array from the source code\&.
