.TH "main.c" 3 "Mon Sep 25 2017" "Version 0.1.3" "C-Array" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'carray\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTRING_OF_INT_SIZE\fP   32"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBchara_of_Int\fP (\fBtype\fP val)"
.br
.ti -1c
.RI "char * \fBchara_of_String\fP (\fBtype\fP val)"
.br
.ti -1c
.RI "int \fBmain_a\fP (int argc, char **argv)"
.br
.ti -1c
.RI "int \fBmain_b\fP (int argc, char **argv)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define STRING_OF_INT_SIZE   32"

.PP
Definition at line 6 of file main\&.c\&.
.SH "Function Documentation"
.PP 
.SS "char* chara_of_Int (\fBtype\fP val)"

.PP
Definition at line 12 of file main\&.c\&.
.SS "char* chara_of_String (\fBtype\fP val)"

.PP
Definition at line 19 of file main\&.c\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 59 of file main\&.c\&.
.SS "int main_a (int argc, char ** argv)"

.PP
Definition at line 26 of file main\&.c\&.
.SS "int main_b (int argc, char ** argv)"

.PP
Definition at line 50 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Array from the source code\&.
