.TH "cvector" 3 "Mon May 14 2018" "Version 0.2.0" "CVector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cvector
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cvector_interface\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "index_t \fB_size\fP"
.br
.ti -1c
.RI "index_t \fB_space\fP"
.br
.ti -1c
.RI "value_t * \fB_vector\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main struct holding the cvector structure\&. 
.PP
Definition at line 190 of file cvector_interface\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CVector from the source code\&.
