.TH "lib/cvector_core.h" 3 "Mon May 14 2018" "Version 0.2.0" "C-Array" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/cvector_core.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <inttypes\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB__cvector_setspace\fP (\fBcvector\fP *p_cvector, \fBindex_t\fP new_space)"
.br
.ti -1c
.RI "void \fB__cvector_shrink\fP (\fBcvector\fP *p_cvector)"
.br
.ti -1c
.RI "void \fB__cvector_extend\fP (\fBcvector\fP *p_cvector)"
.br
.ti -1c
.RI "void \fBcvector_readjust\fP (\fBcvector\fP *p_cvector)"
.br
.ti -1c
.RI "void \fBcvector_addspace\fP (\fBcvector\fP *p_cvector)"
.br
.ti -1c
.RI "\fBcvector\fP * \fBcvector_new\fP ()"
.br
.ti -1c
.RI "\fBcvector\fP * \fBcvector_new_space\fP (\fBindex_t\fP space)"
.br
.ti -1c
.RI "\fBcvector\fP * \fBcvector_new_copy\fP (\fBcvector\fP *p_original)"
.br
.ti -1c
.RI "\fBcvector\fP * \fBcvector_new_copy_space\fP (\fBcvector\fP *p_original, \fBindex_t\fP space)"
.br
.ti -1c
.RI "void \fBcvector_free\fP (\fBcvector\fP *p_cvector)"
.br
.ti -1c
.RI "void \fBcvector_free_func\fP (\fBcvector\fP *p_vector, void(*free_value)(\fBvalue_t\fP))"
.br
.ti -1c
.RI "\fBindex_t\fP \fBcvector_getsize\fP (\fBcvector\fP *p_cvector)"
.br
.ti -1c
.RI "void \fBcvector_add\fP (\fBcvector\fP *p_cvector, \fBvalue_t\fP value)"
.br
.ti -1c
.RI "void \fBcvector_addi\fP (\fBcvector\fP *p_cvector, \fBvalue_t\fP value, \fBindex_t\fP index)"
.br
.ti -1c
.RI "void \fBcvector_insert\fP (\fBcvector\fP *p_cvector, \fBvalue_t\fP value)"
.br
.ti -1c
.RI "\fBvalue_t\fP \fBcvector_remove\fP (\fBcvector\fP *p_cvector)"
.br
.ti -1c
.RI "\fBvalue_t\fP \fBcvector_removei\fP (\fBcvector\fP *p_cvector, \fBindex_t\fP index)"
.br
.ti -1c
.RI "\fBvalue_t\fP \fBcvector_drop\fP (\fBcvector\fP *p_cvector)"
.br
.ti -1c
.RI "void \fBcvector_clear\fP (\fBcvector\fP *p_cvector)"
.br
.ti -1c
.RI "\fBvalue_t\fP \fBcvector_get\fP (\fBcvector\fP *p_cvector, \fBindex_t\fP index)"
.br
.ti -1c
.RI "\fBvalue_t\fP \fBcvector_safeget\fP (\fBcvector\fP *p_cvector, \fBindex_t\fP index)"
.br
.ti -1c
.RI "void \fBcvector_set\fP (\fBcvector\fP *p_cvector, \fBvalue_t\fP value, \fBindex_t\fP index)"
.br
.ti -1c
.RI "void \fBcvector_safeset\fP (\fBcvector\fP *p_cvector, \fBvalue_t\fP value, \fBindex_t\fP index)"
.br
.ti -1c
.RI "void \fBcvector_appendto\fP (\fBcvector\fP *p_cvector, \fBcvector\fP *p_add)"
.br
.ti -1c
.RI "\fBcvector\fP * \fBcvector_concat\fP (\fBcvector\fP *p_cvector_1, \fBcvector\fP *p_cvector_2)"
.br
.ti -1c
.RI "\fBcvector\fP * \fBcvector_reversed\fP (\fBcvector\fP *p_cvector)"
.br
.ti -1c
.RI "\fBhash_t\fP \fBcvector_hash\fP (\fBcvector\fP *p_cvector, \fBhash_t\fP(*hash_value)(\fBvalue_t\fP))"
.br
.ti -1c
.RI "bool \fBcvector_equal\fP (\fBcvector\fP *p_cvector_1, \fBcvector\fP *p_cvector_2)"
.br
.ti -1c
.RI "bool \fBcvector_equal_func\fP (\fBcvector\fP *p_cvector_1, \fBcvector\fP *p_cvector_2, bool(*equal_value)(\fBvalue_t\fP, \fBvalue_t\fP))"
.br
.ti -1c
.RI "\fBvalue_t\fP * \fBcvector_toarray\fP (\fBcvector\fP *p_cvector)"
.br
.ti -1c
.RI "bool \fBcvector_replace\fP (\fBcvector\fP *p_cvector, \fBvalue_t\fP original, \fBvalue_t\fP replacement)"
.br
.ti -1c
.RI "bool \fBcvector_replace_func\fP (\fBcvector\fP *p_cvector, \fBvalue_t\fP original, \fBvalue_t\fP replacement, bool(*equal_value)(\fBvalue_t\fP, \fBvalue_t\fP))"
.br
.ti -1c
.RI "void \fBcvector_sort\fP (\fBcvector\fP *p_cvector, int(*comp_value)(const void *, const void *))"
.br
.ti -1c
.RI "\fBindex_t\fP \fBcvector_indexof\fP (\fBcvector\fP *p_cvector, \fBvalue_t\fP value)"
.br
.ti -1c
.RI "\fBindex_t\fP \fBcvector_indexof_func\fP (\fBcvector\fP *p_cvector, \fBvalue_t\fP value, bool(*equal_value)(\fBvalue_t\fP, \fBvalue_t\fP))"
.br
.ti -1c
.RI "bool \fBcvector_in\fP (\fBcvector\fP *p_cvector, \fBvalue_t\fP value)"
.br
.ti -1c
.RI "bool \fBcvector_in_func\fP (\fBcvector\fP *p_cvector, \fBvalue_t\fP value, bool(*equal_value)(\fBvalue_t\fP, \fBvalue_t\fP))"
.br
.ti -1c
.RI "\fBcvector\fP * \fBcvector_slice\fP (\fBcvector\fP *p_cvector, \fBindex_t\fP from, \fBindex_t\fP to, \fBindex_t\fP step)"
.br
.ti -1c
.RI "\fBvalue_t\fP * \fBcvector_slicetoarray\fP (\fBcvector\fP *p_cvector, \fBindex_t\fP from, \fBindex_t\fP to, \fBindex_t\fP step)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void __cvector_extend (\fBcvector\fP * p_cvector)"
Extends the specified cvector without any check about its size\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.RE
.PP

.PP
Definition at line 35 of file cvector_core\&.h\&.
.SS "void __cvector_setspace (\fBcvector\fP * p_cvector, \fBindex_t\fP new_space)"
Sets space of the specified cvector to new_space 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fInew_space\fP the new space for the specified cvector 
.RE
.PP

.PP
Definition at line 14 of file cvector_core\&.h\&.
.SS "void __cvector_shrink (\fBcvector\fP * p_cvector)"
Shrinks the specified cvector without any check about its size\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.RE
.PP

.PP
Definition at line 26 of file cvector_core\&.h\&.
.SS "void cvector_add (\fBcvector\fP * p_cvector, \fBvalue_t\fP value)"
Adds the specified element at the end of the cvector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIvalue\fP the value to push at the end of the cvector 
.RE
.PP

.PP
Definition at line 190 of file cvector_core\&.h\&.
.SS "void cvector_addi (\fBcvector\fP * p_cvector, \fBvalue_t\fP value, \fBindex_t\fP index)"
Adds the specified element a the position index in the cvector, and shift following elements to the right\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIvalue\fP the value to push a the position index in the cvector 
.br
\fIindex\fP the index where the specified value will be inserted 
.RE
.PP

.PP
Definition at line 207 of file cvector_core\&.h\&.
.SS "void cvector_addspace (\fBcvector\fP * p_cvector)"
Adds space (according to the DEFAULT_ADDSPACE_FACTOR) to the specified cvector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector to extend\&. 
.RE
.PP

.PP
Definition at line 59 of file cvector_core\&.h\&.
.SS "void cvector_appendto (\fBcvector\fP * p_cvector, \fBcvector\fP * p_add)"
Appends element of the cvector pointed by p_add at the end of the cvector pointed by p_cvector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector where elements will be appended 
.br
\fIp_add\fP a pointer to the cvector containing elements to copy 
.RE
.PP

.PP
Definition at line 438 of file cvector_core\&.h\&.
.SS "void cvector_clear (\fBcvector\fP * p_cvector)"
Removes all elements of the cvector without changing its space (that is to say without calling cvector_readjust)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.RE
.PP

.PP
Definition at line 323 of file cvector_core\&.h\&.
.SS "\fBcvector\fP* cvector_concat (\fBcvector\fP * p_cvector_1, \fBcvector\fP * p_cvector_2)"
Returns a new cvector which is the concatenation of the two specified cvectors 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector_1\fP a pointer to the first cvector to concatenate 
.br
\fIp_cvector_2\fP a pointer to the first cvector to concatenate 
.RE
.PP
\fBReturns:\fP
.RS 4
a pointer to the resulting cvector 
.RE
.PP

.PP
Definition at line 459 of file cvector_core\&.h\&.
.SS "\fBvalue_t\fP cvector_drop (\fBcvector\fP * p_cvector)"
Removes the first element of the cvector\&. If the cvector is empty, prints an error anrd returns DEFAULT_VALUE\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.RE
.PP
\fBReturns:\fP
.RS 4
the remove (first) element, or DEFAULT_VALUE if an error occurs 
.RE
.PP

.PP
Definition at line 314 of file cvector_core\&.h\&.
.SS "bool cvector_equal (\fBcvector\fP * p_cvector_1, \fBcvector\fP * p_cvector_2)"
Returns true iif both specified cvectors are equal\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector_1\fP a pointer to the first cvector to test 
.br
\fIp_cvector_2\fP a pointer to the second cvector to test 
.RE
.PP
\fBReturns:\fP
.RS 4
true if both specified cvectors are equal, false otherwise 
.RE
.PP

.PP
Definition at line 517 of file cvector_core\&.h\&.
.SS "bool cvector_equal_func (\fBcvector\fP * p_cvector_1, \fBcvector\fP * p_cvector_2, bool(*)(\fBvalue_t\fP, \fBvalue_t\fP) equal_value)"
Returns true iif both specified cvectors are equal according to the specified test function for values\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector_1\fP a pointer to the first cvector to test 
.br
\fIp_cvector_2\fP a pointer to the second cvector to test 
.br
\fIequal_value\fP the test function for values\&. Its signature must be bool equal_value(value_t value_1, value_t value_2) 
.RE
.PP
\fBReturns:\fP
.RS 4
true if both specified cvectors are equal according to the test function, false otherwise 
.RE
.PP

.PP
Definition at line 540 of file cvector_core\&.h\&.
.SS "void cvector_free (\fBcvector\fP * p_cvector)"
Frees the specified cvector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector to free 
.RE
.PP

.PP
Definition at line 156 of file cvector_core\&.h\&.
.SS "void cvector_free_func (\fBcvector\fP * p_vector, void(*)(\fBvalue_t\fP) free_value)"
Applies the specified free function of each value of the cvector, and then frees it too\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_vector\fP a pointer to the cvector to free 
.br
\fIfree_value\fP the function to free each value of the cvector 
.RE
.PP

.PP
Definition at line 167 of file cvector_core\&.h\&.
.SS "\fBvalue_t\fP cvector_get (\fBcvector\fP * p_cvector, \fBindex_t\fP index)"
Returns the value at the specified index in the cvector\&. Prints an error message and returns DEFAULT_VALUE if the specified index is invalid\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIindex\fP the index of the value to get 
.RE
.PP
\fBReturns:\fP
.RS 4
the desired value if the index is correct, DEFAULT_VALUE otherwise 
.RE
.PP

.PP
Definition at line 334 of file cvector_core\&.h\&.
.SS "\fBindex_t\fP cvector_getsize (\fBcvector\fP * p_cvector)"
Size getter\&. Returns the size of the cvector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.RE
.PP
\fBReturns:\fP
.RS 4
the size of the cvector 
.RE
.PP

.PP
Definition at line 181 of file cvector_core\&.h\&.
.SS "\fBhash_t\fP cvector_hash (\fBcvector\fP * p_cvector, \fBhash_t\fP(*)(\fBvalue_t\fP) hash_value)"
Returns the hash of the specified cvector, using djb2 algorithm by Dan Bernstein, according to the specified hash function for values of the cvector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector to hash 
.br
\fIhash_value\fP hash function for values of the cvector\&. Signature of the hash value function must be hash_t hash_value(value_t value) 
.RE
.PP
\fBReturns:\fP
.RS 4
the computed hash of the specified cvector 
.RE
.PP

.PP
Definition at line 502 of file cvector_core\&.h\&.
.SS "bool cvector_in (\fBcvector\fP * p_cvector, \fBvalue_t\fP value)"
Returns true iif the specified value was found in the cvector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIvalue\fP the value to found 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the value was found, false otherwise 
.RE
.PP

.PP
Definition at line 683 of file cvector_core\&.h\&.
.SS "bool cvector_in_func (\fBcvector\fP * p_cvector, \fBvalue_t\fP value, bool(*)(\fBvalue_t\fP, \fBvalue_t\fP) equal_value)"
Returns true iif the specified value was found in the cvector according to the specified test function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIvalue\fP the value to found 
.br
\fIequal_value\fP the test function to check equality between values\&. Its signature must be bool equal_value(value_t value_1, value_t value_2) 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the value was found, false otherwise 
.RE
.PP

.PP
Definition at line 697 of file cvector_core\&.h\&.
.SS "\fBindex_t\fP cvector_indexof (\fBcvector\fP * p_cvector, \fBvalue_t\fP value)"
Returns the first index where the specified value is found in the cvector\&. If the value is not found, returns NOT_FOUND_INDEX value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIvalue\fP the value to found 
.RE
.PP
\fBReturns:\fP
.RS 4
the first index where the specified value was found, or NOT_FOUND_INDEX if it was not found 
.RE
.PP

.PP
Definition at line 644 of file cvector_core\&.h\&.
.SS "\fBindex_t\fP cvector_indexof_func (\fBcvector\fP * p_cvector, \fBvalue_t\fP value, bool(*)(\fBvalue_t\fP, \fBvalue_t\fP) equal_value)"
Returns the first index where the specified value is found, according to the specified test function\&. Il the value is not found, returns NOT_FOUND_INDEX value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIvalue\fP the value to found 
.br
\fIequal_value\fP the test function to check equality between values\&. Its signature must be bool equal_value(value_t value_1, value_t value_2) 
.RE
.PP
\fBReturns:\fP
.RS 4
the first index where the specified value was found, or NOT_FOUND_INDEX if it was not found 
.RE
.PP

.PP
Definition at line 666 of file cvector_core\&.h\&.
.SS "void cvector_insert (\fBcvector\fP * p_cvector, \fBvalue_t\fP value)"
Adds the specified value at the beginning of the cvector, and shift following elements to the right\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIvalue\fP the value to add at the beginning of the cvector 
.RE
.PP

.PP
Definition at line 242 of file cvector_core\&.h\&.
.SS "\fBcvector\fP* cvector_new ()"
Creates a new cvector which can hold at the beginning at least DEFAULT_INIT_SPACE elements\&. 
.PP
\fBReturns:\fP
.RS 4
a pointer to the new cvector 
.RE
.PP

.PP
Definition at line 71 of file cvector_core\&.h\&.
.SS "\fBcvector\fP* cvector_new_copy (\fBcvector\fP * p_original)"
Creates a new cvector which is a copy of the specified one\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_original\fP a pointer to the cvector to copy 
.RE
.PP
\fBReturns:\fP
.RS 4
a pointer to the new (clone) cvector 
.RE
.PP

.PP
Definition at line 106 of file cvector_core\&.h\&.
.SS "\fBcvector\fP* cvector_new_copy_space (\fBcvector\fP * p_original, \fBindex_t\fP space)"
Creates a new cvector which is a copy of the specified one and which can hold at least space elements\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_original\fP a pointer to the cvector to copy 
.br
\fIspace\fP desired space for the new (clone) cvector\&. space must be greater or equal than the size of the original cvector 
.RE
.PP
\fBReturns:\fP
.RS 4
a pointer to the new (clone) cvector 
.RE
.PP

.PP
Definition at line 127 of file cvector_core\&.h\&.
.SS "\fBcvector\fP* cvector_new_space (\fBindex_t\fP space)"
Creates a new cvector which can hold at the beginning at least space elements\&. 
.PP
\fBParameters:\fP
.RS 4
\fIspace\fP desired space for the new cvector 
.RE
.PP
\fBReturns:\fP
.RS 4
a pointer to the new cvector 
.RE
.PP

.PP
Definition at line 86 of file cvector_core\&.h\&.
.SS "void cvector_readjust (\fBcvector\fP * p_cvector)"
Readjusts space of the specified cvector if needed, according to SHRINK_THRESHOLD and EXTEND_THRESHOLD\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.RE
.PP

.PP
Definition at line 45 of file cvector_core\&.h\&.
.SS "\fBvalue_t\fP cvector_remove (\fBcvector\fP * p_cvector)"
Removes the last element of the cvector and returns it\&. If the cvector is empty, prints an error and returns DEFAULT_VALUE\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.RE
.PP
\fBReturns:\fP
.RS 4
The last value of the cvector if it is not empty, DEFAULT_VALUE otherwise 
.RE
.PP

.PP
Definition at line 253 of file cvector_core\&.h\&.
.SS "\fBvalue_t\fP cvector_removei (\fBcvector\fP * p_cvector, \fBindex_t\fP index)"
Removes the element located at the specified index, and returns it\&. If the cvector is empty or if the index is incorrect, prints an error and returns DEFAULT_VALUE\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIindex\fP the index where the element will be removed 
.RE
.PP
\fBReturns:\fP
.RS 4
the removed element or DEFAULT_VALUE if an error occurs 
.RE
.PP

.PP
Definition at line 274 of file cvector_core\&.h\&.
.SS "bool cvector_replace (\fBcvector\fP * p_cvector, \fBvalue_t\fP original, \fBvalue_t\fP replacement)"
Replace specified elements in the cvector and returns true if at least one change was made\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIoriginal\fP original value to replace 
.br
\fIreplacement\fP replacement value for original 
.RE
.PP
\fBReturns:\fP
.RS 4
true if at least one replacement was made, false otherwise 
.RE
.PP

.PP
Definition at line 580 of file cvector_core\&.h\&.
.SS "bool cvector_replace_func (\fBcvector\fP * p_cvector, \fBvalue_t\fP original, \fBvalue_t\fP replacement, bool(*)(\fBvalue_t\fP, \fBvalue_t\fP) equal_value)"
Replace specified elements in the cvector and returns true if at least one change was made\&. Test between elements of the cvector and original are made with the specified function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIoriginal\fP original value to replace 
.br
\fIreplacement\fP replacement value for original 
.br
\fIequal_value\fP test function used to compare cvector elements and original\&. Its signature must be bool equal_value(value_t value_1, value_t value_2) 
.RE
.PP
\fBReturns:\fP
.RS 4
true if at least one replacement was made, false otherwise 
.RE
.PP

.PP
Definition at line 604 of file cvector_core\&.h\&.
.SS "\fBcvector\fP* cvector_reversed (\fBcvector\fP * p_cvector)"
Returns a cvector which contains the same elements as the specified one, but in a reversed order\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the original cvector 
.RE
.PP
\fBReturns:\fP
.RS 4
the resulting cvector, containing elements of the specified cvector in a reverse order 
.RE
.PP

.PP
Definition at line 479 of file cvector_core\&.h\&.
.SS "\fBvalue_t\fP cvector_safeget (\fBcvector\fP * p_cvector, \fBindex_t\fP index)"
Returns the value at the specified index in the cvector\&. Only prints a warning and returns DEFAULT_VALUE if the specified index is invalid\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIindex\fP the index of the value to get 
.RE
.PP
\fBReturns:\fP
.RS 4
the desired value if the index is correct, DEFAULT_VALUE otherwise 
.RE
.PP

.PP
Definition at line 358 of file cvector_core\&.h\&.
.SS "void cvector_safeset (\fBcvector\fP * p_cvector, \fBvalue_t\fP value, \fBindex_t\fP index)"
Sets the value of the element located at the specified position\&. Only raises warning if the index is invalid, or extends the cvector to be able to set the value at the specified index\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIvalue\fP the value which will be inserted at the index position 
.br
\fIindex\fP the index where the value will be set 
.RE
.PP

.PP
Definition at line 406 of file cvector_core\&.h\&.
.SS "void cvector_set (\fBcvector\fP * p_cvector, \fBvalue_t\fP value, \fBindex_t\fP index)"
Sets the value of the element located at the specified index\&. Raises error if the specified index is invalid\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIvalue\fP the value which will be placed at the index position 
.br
\fIindex\fP the index where the value will be set 
.RE
.PP

.PP
Definition at line 382 of file cvector_core\&.h\&.
.SS "\fBcvector\fP* cvector_slice (\fBcvector\fP * p_cvector, \fBindex_t\fP from, \fBindex_t\fP to, \fBindex_t\fP step)"
Returns the slice [|from:to[| of the specified cvector\&. Prints an error and return NULL if indexes are incorrect\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIfrom\fP index of the begin of the slice, included 
.br
\fIto\fP index of the end of the slice, excluded 
.br
\fIstep\fP step of the slice 
.RE
.PP
\fBReturns:\fP
.RS 4
the corresponding (cvector) slice 
.RE
.PP

.PP
Definition at line 714 of file cvector_core\&.h\&.
.SS "\fBvalue_t\fP* cvector_slicetoarray (\fBcvector\fP * p_cvector, \fBindex_t\fP from, \fBindex_t\fP to, \fBindex_t\fP step)"
Returns the slice [|from:to[| of the specified cvector as a c-style array\&. Prints an error and return NULL if indexes are incorrect\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIfrom\fP index of the begin of the slice, included 
.br
\fIto\fP index of the end of the slice, excluded 
.br
\fIstep\fP step of the slice 
.RE
.PP
\fBReturns:\fP
.RS 4
the corresponding (c-style array) slice 
.RE
.PP

.PP
Definition at line 764 of file cvector_core\&.h\&.
.SS "void cvector_sort (\fBcvector\fP * p_cvector, int(*)(const void *, const void *) comp_value)"
Sorts the elements in the cvector according to the specified comparison function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.br
\fIcomp_value\fP a comparison function which must have the signature int comp_value(const void *p_a, const void *p_b) and which must
.IP "\(bu" 2
return -1 if element a should be placed before element b
.IP "\(bu" 2
return 0 if element a and b could be placed at the same position
.IP "\(bu" 2
return 1 if element a should be placed after element b 
.PP
.RE
.PP

.PP
Definition at line 629 of file cvector_core\&.h\&.
.SS "\fBvalue_t\fP* cvector_toarray (\fBcvector\fP * p_cvector)"
Returns a pointer to a c-style array holding the same elements as the specified cvector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp_cvector\fP a pointer to the cvector 
.RE
.PP
\fBReturns:\fP
.RS 4
a c-style malloc-ed array holding the same elements as the specified cvector, which must be freed after use 
.RE
.PP

.PP
Definition at line 562 of file cvector_core\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Array from the source code\&.
